<a href="https://colab.research.google.com/github/mitsha-microsoft/Deep-RL-Hands-On/blob/master/Chp2_OpenAI_Setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
reqs = '''atari-py==0.2.6
gym==0.15.3
numpy==1.17.2
opencv-python==4.1.1.26
tensorboard==2.0.1
torch==1.3.0
torchvision==0.4.1
pytorch-ignite==0.2.1
tensorboardX==1.9
tensorflow==2.0.0
ptan==0.6'''


In [0]:
f = open('requirements.txt','w')

In [4]:
f.write(reqs)

184

In [0]:
f.close()

In [6]:
!pip install -r requirements.txt

     |████████████████████████████████| 1.6MB 2.7MB/s 
     |████████████████████████████████| 20.4MB 1.3MB/s 
     |████████████████████████████████| 28.7MB 94kB/s 
     |████████████████████████████████| 3.8MB 37.7MB/s 
     |████████████████████████████████| 773.1MB 22kB/s 
     |████████████████████████████████| 10.1MB 90kB/s 
     |████████████████████████████████| 92kB 11.9MB/s 
     |████████████████████████████████| 194kB 49.0MB/s 
     |████████████████████████████████| 86.3MB 53kB/s 
     |████████████████████████████████| 1.0MB 35.1MB/s 
     |████████████████████████████████| 450kB 42.6MB/s 
  Created wheel for gym: filename=gym-0.15.3-cp36-none-any.whl size=1644969 sha256=20aead642672768a7923fadc02699b865dd822bbfc10f554aae89fd15f59488b
  Stored in directory: /root/.cache/pip/wheels/8a/71/10/30f9b16332ecfd6318ac290445c696fe809bcbe40a05f9a799
  Created wheel for ptan: filename=ptan-0.6-cp36-none-any.whl size=23502 sha256=6d01e4c25f39c7d03cbbf81a25cbda2304e08a6cc4b87d9745d9a0

In [0]:
import gym

In [0]:
# Simulating a CartPole Environment
e = gym.make('CartPole-v0')

In [0]:
obs = e.reset()

In [10]:
obs

array([ 0.04166114, -0.00304449, -0.02404054,  0.03823413])

In [11]:
e.step(0)

(array([ 0.04160025, -0.1978136 , -0.02327586,  0.32323613]), 1.0, False, {})

In [0]:
total_reward = 0.0

In [0]:
total_steps = 0

In [15]:
e.reset()

array([ 0.00684296,  0.01772539, -0.02050888, -0.02089601])

In [20]:
total_steps = 0
total_reward = 0.0
e.reset()
while True:
  action = e.action_space.sample()
  obs, reward, done, _ = e.step(action)
  total_reward += reward
  total_steps += 1
  if done:
    break
print("Episode done in {0} steps with a total reward of {1}".format(total_steps,total_reward))

Episode done in 10 steps with a total reward of 10.0
